name: BetterShops
description: $description
version: '${version}'
main: ru.deelter.bettershops.BetterShops

api-version: '1.21'
load: POSTWORLD
author: DeelTer
website: https://deelter.ru

depend: [ MultiEconomy, NBTAPI ]
softdepend:
  - MiniPlaceholders

commands:
  shop:
    aliases: [shops, market]
    usage: /shop <open|reload>